In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_curve, roc_auc_score, classification_report, accuracy_score, confusion_matrix 
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

data = pd.read_csv('dermatology.data')

data.drop(data.columns[[0,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,
                       21,22,23,24,25,26,27,28,29,30,31,]], axis=1, inplace=True)

data.rename(columns = {'0.7':'melanin incontinence','0.24':'band-like infiltrate','55':'age','2.3':'target',}, inplace = True)

data.drop(data[data['age'] == '?'].index, inplace = True)
data['age'] = data['age'].astype(float)

x = data.iloc[:,0:3]
y = data.iloc[:,-1]



from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
print('accuracy: ',ac)

from sklearn.metrics import confusion_matrix

cf_matrix = confusion_matrix(y_test, y_pred)

print('confusion matrix:\n',cf_matrix)


accuracy:  0.4305555555555556
confusion matrix:
 [[17  1  0  0  1  2]
 [10  0  0  1  0  1]
 [ 4  1  7  0  0  0]
 [ 6  2  0  1  0  1]
 [10  0  0  0  1  1]
 [ 0  0  0  0  0  5]]
